# Generated by Django 6.0 on 2025-12-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appuntamenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora_pagamento', models.DateTimeField(auto_now_add=True)),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sconto_applicato', models.DecimalField(decimal_places=2, default=0.0, help_text='Sconto in Euro', max_digits=5)),
                ('metodo_pagamento', models.CharField(choices=[('contanti', 'Contanti'), ('carta', 'Carta'), ('bancomat', 'Bancomat'), ('satispay', 'Satispay'), ('bonifico', 'Bonifico Bancario')], default='contanti', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('appuntamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transazione', to='appuntamenti.appuntamento')),
            ],
            options={
                'verbose_name_plural': 'Transazioni',
                'ordering': ['-data_ora_pagamento'],
            },
        ),
    ]
