# Generated by Django 6.0 on 2025-12-15 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuntamenti', '0001_initial'),
        ('cassa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transazione',
            name='appuntamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transazione', to='appuntamenti.appuntamento'),
        ),
        migrations.AlterField(
            model_name='transazione',
            name='metodo_pagamento',
            field=models.CharField(choices=[('contanti', 'Contanti'), ('carta', 'Carta'), ('satispay', 'Satispay'), ('bonifico', 'Bonifico Bancario')], default='contanti', max_length=20),
        ),
    ]
