# Generated by Django 6.0 on 2025-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('data_iscrizione', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('stipendio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_assunzione', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
    ]
