# Generated by Django 6.0 on 2025-12-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0001_initial'),
        ('servizi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora_inizio', models.DateTimeField()),
                ('data_ora_fine', models.DateTimeField()),
                ('stato', models.CharField(choices=[('prenotato', 'Prenotato'), ('in_corso', 'In Corso'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='prenotato', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appuntamenti', to='anagrafica.cliente')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appuntamenti', to='anagrafica.dipendente')),
            ],
            options={
                'verbose_name_plural': 'Appuntamenti',
                'ordering': ['-data_ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioAppuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_finale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('durata_effettiva', models.PositiveIntegerField(help_text='Durata effettiva in minuti')),
                ('appuntamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='appuntamenti.appuntamento')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettagli_appuntamento', to='servizi.servizio')),
            ],
            options={
                'verbose_name_plural': 'Dettagli Appuntamenti',
            },
        ),
    ]
