# Generated by Django 6.0 on 2025-12-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuntamenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='motivo_annullamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
