# Generated by Django 6.0 on 2025-12-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuntamenti', '0002_appuntamento_motivo_annullamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='promemoria_inviato',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LogNotifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('destinatario', models.CharField(max_length=255)),
                ('messaggio', models.TextField()),
                ('data_ora_invio', models.DateTimeField(auto_now_add=True)),
                ('successo', models.BooleanField(default=True)),
                ('appuntamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_log', to='appuntamenti.appuntamento')),
            ],
            options={
                'verbose_name_plural': 'Log Notifiche',
                'ordering': ['-data_ora_invio'],
            },
        ),
    ]
