# Generated by Django 6.0 on 2025-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
                ('durata_minuti', models.PositiveIntegerField(help_text='Durata standard del servizio in minuti')),
                ('prezzo', models.DecimalField(decimal_places=2, help_text='Prezzo standard in Euro', max_digits=8)),
                ('attivo', models.BooleanField(default=True, help_text='Se False, il servizio non sarà prenotabile')),
            ],
            options={
                'verbose_name_plural': 'Servizi',
                'ordering': ['nome'],
            },
        ),
    ]
